export const bucketActionTypes = {
  GET_BUCKETS_SUCCESS: 'GET_BUCKETS_SUCCESS',
  GET_BUCKETS_FAIL: 'GET_BUCKETS_FAIL',
  CREATE_BUCKET_SUCCESS: 'CREATE_BUCKET_SUCCESS',
  CREATE_BUCKET_FAIL: 'CREATE_BUCKET_FAIL',
};
