export const fileActionTypes = {
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  UPLOAD_FILE_FAIL: 'UPLOAD_FILE_FAIL',
  GET_FILES_SUCCESS: 'GET_FILES_SUCCESS',
  GET_FILES_FAIL: 'GET_FILES_FAIL',
};
