export const renderActionTypes = {
  CREATE_NEW_BUCKET_ON: 'CREATE_NEW_BUCKET_ON',
  CREATE_NEW_BUCKET_OFF: 'CREATE_NEW_BUCKET_OFF',
  SET_BUCKET: 'SET_BUCKET',
  REMOVE_BUCKET: 'REMOVE_BUCKET',
  FILES_ON: 'FILES_ON',
  FILES_OFF: 'FILES_OFF',
  BUCKET_DETAILS_ON: 'BUCKET_DETAILS_ON',
  BUCKET_DETAILS_OFF: 'BUCKET_DETAILS_OFF',
};
